#include "WanaWorksAutoRetargetActions.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "Engine/SkeletalMesh.h"
#include "HAL/FileManager.h"
#include "Misc/PackageName.h"
#include "Misc/Paths.h"
#include "Retargeter/IKRetargeter.h"
#include "RetargetEditor/IKRetargeterController.h"
#include "Rig/IKRigDefinition.h"
#include "RigEditor/IKRigAutoCharacterizer.h"
#include "RigEditor/IKRigController.h"
#include "UObject/Package.h"
#include "UObject/SavePackage.h"

namespace
{
const TCHAR* WanaWorksRetargetRootPath = TEXT("/Game/WanaWorks/Retarget");

FString SanitizeWanaRetargetAssetNameFragment(const FString& InName)
{
    FString Result;
    Result.Reserve(InName.Len());

    for (const TCHAR Character : InName)
    {
        Result.AppendChar(FChar::IsAlnum(Character) ? Character : TEXT('_'));
    }

    return Result.IsEmpty() ? TEXT("Unnamed") : Result;
}

bool SaveWanaRetargetPackage(UPackage* Package, UObject* Asset, const FString& PackagePath)
{
    if (!Package || !Asset)
    {
        return false;
    }

    Package->MarkPackageDirty();

    const FString PackageFilename = FPackageName::LongPackageNameToFilename(
        PackagePath,
        FPackageName::GetAssetPackageExtension());
    IFileManager::Get().MakeDirectory(*FPaths::GetPath(PackageFilename), true);

    FSavePackageArgs SaveArgs;
    SaveArgs.TopLevelFlags = RF_Public | RF_Standalone;
    SaveArgs.SaveFlags = SAVE_NoError;

    return UPackage::SavePackage(Package, Asset, *PackageFilename, SaveArgs);
}

// Finds an existing WanaWorks-owned IK Rig for this mesh or creates one, then re-runs UE's
// auto-characterizer against it so the readiness report always reflects the current mesh.
UIKRigDefinition* FindOrCreateWanaRetargetIKRig(
    USkeletalMesh* Mesh,
    const FString& MeshLabel,
    FAutoCharacterizeResults& OutCharacterizeResults,
    FString& OutIKRigAssetPath)
{
    if (!Mesh)
    {
        return nullptr;
    }

    const FString AssetName = FString::Printf(TEXT("IKRig_%s"), *SanitizeWanaRetargetAssetNameFragment(MeshLabel));
    const FString PackagePath = FString::Printf(TEXT("%s/%s"), WanaWorksRetargetRootPath, *AssetName);
    OutIKRigAssetPath = PackagePath;

    UIKRigDefinition* RigAsset = LoadObject<UIKRigDefinition>(nullptr, *FString::Printf(TEXT("%s.%s"), *PackagePath, *AssetName));
    UPackage* Package = RigAsset ? RigAsset->GetOutermost() : CreatePackage(*PackagePath);

    if (!Package)
    {
        return nullptr;
    }

    const bool bCreatedNewAsset = RigAsset == nullptr;

    if (!RigAsset)
    {
        RigAsset = NewObject<UIKRigDefinition>(Package, UIKRigDefinition::StaticClass(), *AssetName, RF_Public | RF_Standalone | RF_Transactional);
    }

    if (!RigAsset)
    {
        return nullptr;
    }

    UIKRigController* Controller = UIKRigController::GetController(RigAsset);

    if (!Controller)
    {
        return nullptr;
    }

    Controller->SetSkeletalMesh(Mesh);
    Controller->AutoGenerateRetargetDefinition(OutCharacterizeResults);
    Controller->ApplyAutoGeneratedRetargetDefinition();

    if (bCreatedNewAsset)
    {
        FAssetRegistryModule::AssetCreated(RigAsset);
    }

    SaveWanaRetargetPackage(Package, RigAsset, PackagePath);

    return RigAsset;
}

FWanaAutoRetargetSideResult BuildSideResult(
    const FString& MeshLabel,
    const FString& IKRigAssetPath,
    const FAutoCharacterizeResults& CharacterizeResults,
    int32 DetectedChainCount)
{
    FWanaAutoRetargetSideResult SideResult;
    SideResult.SkeletalMeshLabel = MeshLabel;
    SideResult.IKRigAssetPath = IKRigAssetPath;
    SideResult.bUsedKnownTemplate = CharacterizeResults.bUsedTemplate;
    SideResult.MatchedTemplateName = CharacterizeResults.BestTemplateName.IsNone()
        ? TEXT("(no known template match)")
        : CharacterizeResults.BestTemplateName.ToString();
    SideResult.TemplateMatchScore = CharacterizeResults.BestPercentageOfTemplateScore;
    SideResult.DetectedChainCount = DetectedChainCount;
    SideResult.MissingBoneCount = CharacterizeResults.MissingBones.Num();
    return SideResult;
}
}

FWanaAutoRetargetResult WanaWorksAutoRetargetActions::ExecuteAutoRetargetAnalysis(
    USkeletalMesh* SourceMesh,
    USkeletalMesh* TargetMesh,
    const FString& SourceLabel,
    const FString& TargetLabel)
{
    FWanaAutoRetargetResult Result;

    if (!SourceMesh || !TargetMesh)
    {
        Result.StatusLabel = TEXT("Retarget Not Supported");
        Result.Detail = TEXT("Auto-retarget needs both a source subject and a target skeletal mesh with valid skeletal meshes.");
        return Result;
    }

    if (SourceMesh == TargetMesh)
    {
        Result.StatusLabel = TEXT("Retarget Not Needed");
        Result.Detail = TEXT("The selected target skeletal mesh is the same as the source subject's mesh.");
        return Result;
    }

    FAutoCharacterizeResults SourceCharacterizeResults;
    FString SourceIKRigAssetPath;
    UIKRigDefinition* SourceRig = FindOrCreateWanaRetargetIKRig(SourceMesh, SourceLabel, SourceCharacterizeResults, SourceIKRigAssetPath);

    FAutoCharacterizeResults TargetCharacterizeResults;
    FString TargetIKRigAssetPath;
    UIKRigDefinition* TargetRig = FindOrCreateWanaRetargetIKRig(TargetMesh, TargetLabel, TargetCharacterizeResults, TargetIKRigAssetPath);

    if (!SourceRig || !TargetRig)
    {
        Result.StatusLabel = TEXT("Retarget Failed");
        Result.Detail = TEXT("WanaWorks could not create the IK Rig definitions needed to characterize one or both skeletons.");
        return Result;
    }

    const UIKRigController* SourceRigController = UIKRigController::GetController(SourceRig);
    const UIKRigController* TargetRigController = UIKRigController::GetController(TargetRig);
    const int32 SourceChainCount = SourceRigController ? SourceRigController->GetRetargetChains().Num() : 0;
    const int32 TargetChainCount = TargetRigController ? TargetRigController->GetRetargetChains().Num() : 0;

    const FString RetargeterAssetName = FString::Printf(
        TEXT("RTG_%s_To_%s"),
        *SanitizeWanaRetargetAssetNameFragment(SourceLabel),
        *SanitizeWanaRetargetAssetNameFragment(TargetLabel));
    const FString RetargeterPackagePath = FString::Printf(TEXT("%s/%s"), WanaWorksRetargetRootPath, *RetargeterAssetName);

    UIKRetargeter* RetargeterAsset = LoadObject<UIKRetargeter>(nullptr, *FString::Printf(TEXT("%s.%s"), *RetargeterPackagePath, *RetargeterAssetName));
    UPackage* RetargeterPackage = RetargeterAsset ? RetargeterAsset->GetOutermost() : CreatePackage(*RetargeterPackagePath);

    if (!RetargeterPackage)
    {
        Result.StatusLabel = TEXT("Retarget Failed");
        Result.Detail = TEXT("WanaWorks could not create the retargeter package.");
        return Result;
    }

    const bool bCreatedNewRetargeter = RetargeterAsset == nullptr;

    if (!RetargeterAsset)
    {
        RetargeterAsset = NewObject<UIKRetargeter>(RetargeterPackage, UIKRetargeter::StaticClass(), *RetargeterAssetName, RF_Public | RF_Standalone | RF_Transactional);
    }

    if (!RetargeterAsset)
    {
        Result.StatusLabel = TEXT("Retarget Failed");
        Result.Detail = TEXT("WanaWorks could not create the retargeter asset.");
        return Result;
    }

    UIKRetargeterController* RetargeterController = UIKRetargeterController::GetController(RetargeterAsset);

    if (!RetargeterController)
    {
        Result.StatusLabel = TEXT("Retarget Failed");
        Result.Detail = TEXT("WanaWorks could not access the retargeter controller.");
        return Result;
    }

    RetargeterController->SetIKRig(ERetargetSourceOrTarget::Source, SourceRig);
    RetargeterController->SetIKRig(ERetargetSourceOrTarget::Target, TargetRig);
    RetargeterController->SetPreviewMesh(ERetargetSourceOrTarget::Source, SourceMesh);
    RetargeterController->SetPreviewMesh(ERetargetSourceOrTarget::Target, TargetMesh);
    // Exact-name matches first (reset cleanly), then fuzzy match anything still unmapped.
    RetargeterController->AutoMapChains(EAutoMapChainType::Exact, true);
    RetargeterController->AutoMapChains(EAutoMapChainType::Fuzzy, false);

    int32 MappedChainCount = 0;
    const TArray<URetargetChainSettings*>& ChainSettings = RetargeterController->GetAllChainSettings();

    for (const URetargetChainSettings* ChainSetting : ChainSettings)
    {
        if (ChainSetting && !ChainSetting->SourceChain.IsNone())
        {
            ++MappedChainCount;
        }
    }

    if (bCreatedNewRetargeter)
    {
        FAssetRegistryModule::AssetCreated(RetargeterAsset);
    }

    SaveWanaRetargetPackage(RetargeterPackage, RetargeterAsset, RetargeterPackagePath);

    Result.Source = BuildSideResult(SourceLabel, SourceIKRigAssetPath, SourceCharacterizeResults, SourceChainCount);
    Result.Target = BuildSideResult(TargetLabel, TargetIKRigAssetPath, TargetCharacterizeResults, TargetChainCount);
    Result.MappedChainCount = MappedChainCount;
    Result.TotalTargetChainCount = ChainSettings.Num();
    Result.RetargeterAssetPath = RetargeterPackagePath;
    Result.bSucceeded = true;

    const bool bFullyMapped = Result.TotalTargetChainCount > 0 && MappedChainCount == Result.TotalTargetChainCount;
    Result.StatusLabel = bFullyMapped
        ? TEXT("Retarget Ready")
        : (MappedChainCount > 0 ? TEXT("Retarget Needs Review") : TEXT("Retarget Limited"));

    Result.Detail = FString::Printf(
        TEXT("WanaWorks auto-characterized both skeletons and mapped %d of %d target chains automatically."),
        MappedChainCount,
        Result.TotalTargetChainCount);

    Result.ReadinessSummaryText = FString::Printf(
        TEXT("Auto-Retarget Readiness\nSource: %s\nSource IK Rig: %s\nSource Template Match: %s (%s, %.0f%% match)\nSource Chains Detected: %d\nSource Missing Bones: %d\nTarget: %s\nTarget IK Rig: %s\nTarget Template Match: %s (%s, %.0f%% match)\nTarget Chains Detected: %d\nTarget Missing Bones: %d\nChain Mapping: %d of %d target chains mapped automatically\nRetargeter Asset: %s\nOriginal Meshes: Preserved (WanaWorks only wrote new assets under %s)"),
        *Result.Source.SkeletalMeshLabel,
        *Result.Source.IKRigAssetPath,
        Result.Source.bUsedKnownTemplate ? TEXT("Known template") : TEXT("Procedural"),
        *Result.Source.MatchedTemplateName,
        Result.Source.TemplateMatchScore * 100.0f,
        Result.Source.DetectedChainCount,
        Result.Source.MissingBoneCount,
        *Result.Target.SkeletalMeshLabel,
        *Result.Target.IKRigAssetPath,
        Result.Target.bUsedKnownTemplate ? TEXT("Known template") : TEXT("Procedural"),
        *Result.Target.MatchedTemplateName,
        Result.Target.TemplateMatchScore * 100.0f,
        Result.Target.DetectedChainCount,
        Result.Target.MissingBoneCount,
        MappedChainCount,
        Result.TotalTargetChainCount,
        *Result.RetargeterAssetPath,
        WanaWorksRetargetRootPath);

    return Result;
}
